site_name: "OQTOPUS Client"
site_description: "Python SDK for OQTOPUS Cloud User API"
repo_name: oqtopus-client
repo_url: "https://github.com/oqtopus-team/oqtopus-client"

nav:
  - Home: index.md
  - Usage:
      - Getting started: usage/getting_started.md
      - OQTOPUS Client Examples: "https://github.com/oqtopus-team/oqtopus-client/tree/main/examples"
  - API reference:
      - oqtopus_client: reference/
  - Developer Guidelines:
      - Setup Development Environment: developer_guidelines/setup.md
      - Development Flow: developer_guidelines/development_flow.md
      - API Model Generation: developer_guidelines/api_model_generation.md
      - Quality Checks: developer_guidelines/quality_checks.md
      - Overview: developer_guidelines/index.md
      - How to Contribute: CONTRIBUTING.md
      - Code of Conduct: "https://oqtopus-team.github.io/code-of-conduct/"
      - Security: "https://oqtopus-team.github.io/security-policy/"

exclude_docs: |
  /api.md
  /models.md
  /quickstart.md
  /examples.md
  /cmd_*.md

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: asset/oqtopus-black_symbol.svg
  favicon: asset/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.follow

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: API_reference.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            relative_crossrefs: true
            scoped_crossrefs: true
            show_bases: false
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            preload_modules: [mkdocstrings]
            show_inheritance_diagram: true
            summary:
              modules: false
              classes: true
              functions: true
              attributes: true
            unwrap_annotated: true
            filters:
              - "!^_"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - admonition
  - footnotes
  - codehilite
  - toc:
      permalink: true

extra_css:
  - "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  - "css/custom.css"

extra_javascript:
  - "js/custom.js"
