[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oqtopus-client"
version = "0.1.0"
description = "Python SDK for OQTOPUS Cloud User API"
readme = "README.md"
license = "Apache-2.0"
authors = [{ name = "oqtopus-team", email = "oqtopus-team@googlegroups.com" }]
keywords = ["quantum", "oqtopus", "sdk", "openapi"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Physics",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
]
requires-python = ">=3.10"
dependencies = [
  "pydantic>=2.7.0",
  "pyyaml>=6.0.0",
  "python-dateutil>=2.5.3",
  "typing-extensions>=4.7.1",
  "urllib3>=1.25.3,<2.1.0",
  "aiohttp>=3.0.0",
  "aiohttp-retry>=2.8.3",
]

[project.urls]
documentation = "https://oqtopus-client.readthedocs.io/"
repository = "https://github.com/oqtopus-team/oqtopus-client"

[project.optional-dependencies]
dev = [
  "ipykernel>=6.29.0",
  "mkdocs>=1.6.0",
  "mkdocs-gen-files>=0.5.0",
  "mkdocs-literate-nav>=0.6.1",
  "mkdocs-material>=9.5.0",
  "mkdocstrings[python]>=0.28.0",
  "mypy>=1.11.0",
  "pytest>=8.0.0",
  "pytest-cov>=5.0.0",
  "ruff>=0.6.0",
  "types-PyYAML>=6.0.12.20241230",
  "types-python-dateutil>=2.9.0.20250516",
]

[tool.pytest.ini_options]
addopts = "--cov=src/oqtopus_client --cov-report=term-missing --cov-fail-under=80"
pythonpath = ["src"]
testpaths = ["tests"]

[tool.coverage.run]
omit = ["src/oqtopus_client/rest/*", "src/oqtopus_client/rest/models/*"]

[tool.ruff]
preview = true
include = ["src/**/*.py", "tests/**/*.py", "scripts/**/*.py", "examples/**/*.py"]
exclude = ["src/oqtopus_client/rest/**"]
lint.select = ["ALL"]
lint.ignore = [
  "COM812",
  "CPY001",
  "D100",
  "D104",
  "D107",
  "D203",
  "D213",
  "ISC001",
]

[tool.ruff.lint.per-file-ignores]
"examples/**/*.py" = [
  "T201",
]
"tests/**/*.py" = [
  "ANN201",
  "ANN205",
  "ANN401",
  "ARG001",
  "ARG005",
  "C901",
  "CPY001",
  "D",
  "E501",
  "PLC2701",
  "PLC1901",
  "PLR0911",
  "PLR0912",
  "PLR0915",
  "PLR2004",
  "PLR6301",
  "PT011",
  "PT018",
  "RUF029",
  "S101",
  "S105",
  "S106",
  "SLF001",
  "TC003",
]

[tool.mypy]
files = ["src", "tests", "examples"]
exclude = "src/oqtopus_client/rest/.*"

[[tool.mypy.overrides]]
module = ["oqtopus_client.rest.*"]
ignore_errors = true

[[tool.mypy.overrides]]
module = ["examples.run_sampling_qiskit", "examples.run_sampling_quri_parts"]
disable_error_code = ["import-not-found"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["oqtopus_client*"]
